services:
  cover:
    image: ${SERVICE_IMAGE_NAME}${SERVICE_IMAGE_TAG:+:${SERVICE_IMAGE_TAG}}${SERVICE_IMAGE_DIGEST:+@${SERVICE_IMAGE_DIGEST}}
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - FOO=${FOO}

networks:
  cover:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.210.0/24
          gateway: 173.17.210.1