name: deploy docker
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        uses: ./.github/actions/deploy/compose
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_private_host: ${{ secrets.SSH_PRIVATE_HOST }}
          ssh_private_port: ${{ secrets.SSH_PRIVATE_PORT }}
          ssh_private_user: ${{ secrets.SSH_PRIVATE_USER }}
          domain_name: covering
          target_service: nginx
          target_port: 80